#!/bin/bash

#NF="'#1d1f21'"
NF="'#fff4a6'"
#NF=white

#NB=black
#NB="'#C5C8C6'"
NB="'#1d1f21'"

SB="'#1d1f21'"

SF="'#C5C8C6'"
SF="'#ffffff'"
#FONT=Terminus-9:normal
FONT=Inconsolata-12:normal

#CMD="dmenu -i -l 40 -w 200 -x 200 -y 80 -nf $NF -nb $NB -sb $SB -sf $SF -dim .8 -fn $FONT"
CMD="dmenu -i -l 40 -w 300 -x 200 -y 80 -nf $NF -nb $NB -sb $SB -sf $SF -fn $FONT"
#exec $CMD
j4-dmenu-desktop --dmenu="$CMD"
